package errorcustom

import (
	"fmt"
	"net/http"
)

// CustomVisionError represents a custom error type for Custom Vision errors
type CustomVisionError struct {
	StatusCode int
	ErrorName  string
	Message    string
}

// Error implements the error interface for CustomVisionError
func (e *CustomVisionError) Error() string {
	return fmt.Sprintf("status code %d: %s - %s", e.StatusCode, e.ErrorName, e.Message)
}

// Mapping of status codes to error names
var ErrorNames = map[int]string{
	http.StatusBadRequest:           "BadRequest",
	http.StatusConflict:             "Conflict",
	http.StatusForbidden:            "Forbidden",
	http.StatusNotFound:             "NotFound",
	http.StatusUnsupportedMediaType: "UnsupportedMediaType",
	http.StatusInternalServerError:  "ErrorServerTimeOut",
	http.StatusServiceUnavailable:   "ErrorFeaturizationServiceUnavailable",
	401:                             "BadRequestClassificationTrainingValidationFailed",
	402:                             "BadRequestCustomBaseModelArchitectureRetired",
	405:                             "BadRequestCustomerManagedKeyRevoked",
	406:                             "BadRequestDetectionTrainingNotAllowNegativeTag",
	407:                             "BadRequestDetectionTrainingValidationFailed",
	408:                             "BadRequestDomainNotSupportedForAdvancedTraining",
	410:                             "BadRequestExceedProjectLimit",
	411:                             "BadRequestExceedTagPerImageLimit",
	412:                             "BadRequestExceedTagPerProjectLimit",
	413:                             "BadRequestExceededBatchSize",
	414:                             "BadRequestExceededQuota",
	416:                             "BadRequestExportPlatformNotSupportedForAdvancedTraining",
	417:                             "BadRequestExportValidationFailed",
	418:                             "BadRequestExportWhileTraining",
	419:                             "BadRequestImageAspectRatio",
	420:                             "BadRequestImageBatch",
	421:                             "BadRequestImageDimensions",
	422:                             "BadRequestImageExceededCount",
	423:                             "BadRequestImageFormat",
	424:                             "BadRequestImageMetadataKey",
	425:                             "BadRequestImageMetadataValue",
	426:                             "BadRequestImageRegions",
	427:                             "BadRequestImageSizeBytes",
	428:                             "BadRequestImageStream",
	429:                             "BadRequestImageTags",
	430:                             "BadRequestImageUrl",
	431:                             "BadRequestInvalid",
	432:                             "BadRequestInvalidArtifactUri",
	433:                             "BadRequestInvalidEmailAddress",
	434:                             "BadRequestInvalidIds",
	435:                             "BadRequestInvalidImportToken",
	436:                             "BadRequestInvalidPublishName",
	437:                             "BadRequestInvalidPublishTarget",
	438:                             "BadRequestInvalidUri",
	439:                             "BadRequestIterationDescription",
	440:                             "BadRequestIterationIsNotTrained",
	441:                             "BadRequestIterationIsPublished",
	442:                             "BadRequestIterationName",
	443:                             "BadRequestIterationNameNotUnique",
	444:                             "BadRequestIterationNotPublished",
	445:                             "BadRequestIterationValidationFailed",
	446:                             "BadRequestMultiClassClassificationTrainingValidationFailed",
	447:                             "BadRequestMultiLabelClassificationTrainingValidationFailed",
	448:                             "BadRequestMultipleGeneralProductTag",
	449:                             "BadRequestMultipleNegativeTag",
	450:                             "BadRequestNegativeAndRegularTagOnSameImage",
	451:                             "BadRequestNotLimitedTrial",
	452:                             "BadRequestNotSupported",
	453:                             "BadRequestOperationNotSupported",
	454:                             "BadRequestPredictionIdsExceededCount",
	455:                             "BadRequestPredictionIdsMissing",
	456:                             "BadRequestPredictionInvalidApplicationName",
	457:                             "BadRequestPredictionInvalidQueryParameters",
	458:                             "BadRequestPredictionResultsExceededCount",
	459:                             "BadRequestPredictionTagsExceededCount",
	460:                             "BadRequestProjectDescription",
	461:                             "BadRequestProjectDuplicated",
	462:                             "BadRequestProjectImagePreprocessingSettings",
	463:                             "BadRequestProjectName",
	464:                             "BadRequestProjectNameNotUnique",
	465:                             "BadRequestProjectUnknownClassification",
	466:                             "BadRequestProjectUnknownDomain",
	467:                             "BadRequestProjectUnsupportedDomainTypeChange",
	468:                             "BadRequestProjectUnsupportedExportPlatform",
	469:                             "BadRequestRequiredParamIsNull",
	470:                             "BadRequestReservedBudgetInHoursNotEnoughForAdvancedTraining",
	471:                             "BadRequestRetiredDomainNotSupportedForTraining",
	472:                             "BadRequestSubscriptionApi",
	473:                             "BadRequestTagDescription",
	474:                             "BadRequestTagName",
	475:                             "BadRequestTagNameNotUnique",
	476:                             "BadRequestTagType",
	477:                             "BadRequestTrainingAlreadyInProgress",
	478:                             "BadRequestTrainingNotNeeded",
	479:                             "BadRequestTrainingNotNeededButTrainingPipelineUpdated",
	480:                             "BadRequestTrainingValidationFailed",
	481:                             "BadRequestUnpublishFailed",
	482:                             "BadRequestUnsupportedDomain",
	483:                             "BadRequestWorkspaceCannotBeModified",
	484:                             "BadRequestWorkspaceNotDeletable",
	485:                             "ConflictInvalid",
	486:                             "ErrorExporterInvalidClassifier",
	487:                             "ErrorExporterInvalidFeaturizer",
	488:                             "ErrorExporterInvalidPlatform",
	489:                             "ErrorFeaturizationAugmentationError",
	490:                             "ErrorFeaturizationAugmentationUnavailable",
	491:                             "ErrorFeaturizationInvalidFeaturizer",
	492:                             "ErrorFeaturizationQueueTimeout",
	493:                             "ErrorFeaturizationServiceUnavailable",
	494:                             "ErrorFeaturizationUnrecognizedJob",
	495:                             "ErrorInvalid",
	496:                             "ErrorIterationCopyFailed",
	497:                             "ErrorPrediction",
	498:                             "ErrorPredictionModelNotCached",
	499:                             "ErrorPredictionModelNotFound",
	501:                             "ErrorPredictionStorage",
	502:                             "ErrorPreparePerformanceMigrationFailed",
	504:                             "ErrorProjectImportRequestFailed",
	505:                             "ErrorProjectInvalidDomain",
	506:                             "ErrorProjectInvalidPipelineConfiguration",
	507:                             "ErrorProjectInvalidWorkspace",
	508:                             "ErrorProjectTrainingRequestFailed",
	509:                             "ErrorRegionProposal",
	510:                             "ErrorServerTimeOut",
	511:                             "ErrorUnknown",
	512:                             "ErrorUnknownBaseModel",
	513:                             "ForbiddenDRModeEnabled",
	514:                             "ForbiddenInvalid",
	515:                             "ForbiddenUser",
	516:                             "ForbiddenUserDisabled",
	517:                             "ForbiddenUserDoesNotExist",
	518:                             "ForbiddenUserInsufficientCapability",
	519:                             "ForbiddenUserResource",
	520:                             "ForbiddenUserSignupAllowanceExceeded",
	521:                             "ForbiddenUserSignupDisabled",
	522:                             "NoError",
	523:                             "NotFoundApimSubscription",
	524:                             "NotFoundDomain",
	525:                             "NotFoundImage",
	526:                             "NotFoundInvalid",
	527:                             "NotFoundIteration",
	528:                             "NotFoundIterationPerformance",
	529:                             "NotFoundProject",
	530:                             "NotFoundProjectDefaultIteration",
	531:                             "NotFoundTag",
}
